changelog:
  exclude:
    labels:
      - skip-release-notes
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Security
      labels:
        - security
    - title: Dependencies and Operations
      labels:
        - dependencies
        - build
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
