name: Docker E2E

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/AgileConfig.Server.UI/react-ui-antd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: src/AgileConfig.Server.UI/react-ui-antd/package-lock.json
      - run: npm ci
      - run: npm run test:e2e:docker
